
var urlBG = require("@/assets/images/map-info-bg@2x.png");
var urlLogo = require("@/assets/images/map-hjjd@2x.png");
var urlClose = require("@/assets/images/tc-close@2x.png");
var tooltip = {
    trigger: "item",
    triggerOn: "click",
    // position: ["7.6%", "24.5%"],
    alwaysShowContent: false,
    backgroundColor: "#042d56",
    padding: 0,
    formatter: function (params) {
      let html = [
        '  <div class="tootip-wrap" style="background: #042d56";over-flow:hidden;>',
        "    <div",
        '      class="wrap"',
        '      style="background:url(' + urlBG + ") no-repeat;",
        "        background-size: contain;",
        "        background-position: center;",
        "            color: #5cdbc5;",
        "            width: 2.58rem;",
        "            height:2.95rem;",
        "            over-flow:hidden;",
        "            padding-top: 0.16rem;",
        '        "',
        "    >",
        '    <div class="top" style="',
        "        width: 100%;",
        "        display: flex;",
        "        justify-content: space-between;",
        "        align-items: center;",
        "        padding: 0 0.16rem;",
        '    ">',
        '      <div class="logo" style="',
        "                background: url(" + urlLogo + ") no-repeat;",
        "                background-size: cover;",
        "                background-position: center;",
        "                width: 0.38rem;",
        "                height: 0.42rem;",
        '            "',
        "      ></div>",
        '      <div class="name-tit" style="',
        "            display: flex;",
        "            flex-direction: column;",
        "            justify-content: center;",
        "            align-items: center;",
        "            margin-right: 0.6rem;",
        '                ">',
        '            <div class="tit" style="',
        "                    font-size: 0.13rem;",
        "                    color: #027d9c;",
        '                ">汇聚节点',
        "            </div>",
        '            <div class="name" style="',
        "                    font-size: 0.18rem;",
        '                ">安徽',
        "            </div>",
        "      </div>",
        '      <div class="close" style="',
        "                background: url(" + urlClose + ") no-repeat;",
        "                background-size: cover;",
        "                background-position: center;",
        "                width: 0.2rem;",
        "                height: 0.2rem;",
        "            margin-top: -0.2rem;",
        "            margin-right: 0rem;",
        '      "></div>',
        "    </div>",
        '    <div class="bottom" style="',
        "        width: 2.1rem;",
        "        margin: auto;",
        '    ">',
        '            <div class="item" style="',
        "                font-size: 0.18rem;",
        "                margin: 0.06rem 0 ;",
        "                font-weight: bold;",
        '            "  >数据总量<span style="',
        "                font-size: 0.2rem;",
        "                font-family: timeFont;",
        "                font-weight: bold;",
        "                letter-spacing: 2px;",
        "                color: white;",
        '                ">123434</span>PB</div>',
  
        '            <div class="item" style="',
        "                font-size: 0.18rem;",
        "                margin: 0.06rem 0 ;",
        "                font-weight: bold;",
        '            "  >数据总量<span style="',
        "                font-size: 0.2rem;",
        "                font-family: timeFont;",
        "                font-weight: bold;",
        "                letter-spacing: 2px;",
        "                color: white;",
        '                ">123434</span>PB</div>',
        
        '            <div class="item" style="',
        "                font-size: 0.18rem;",
        "                margin: 0.06rem 0 ;",
        "                font-weight: bold;",
        '            "  >数据总量<span style="',
        "                font-size: 0.2rem;",
        "                font-family: timeFont;",
        "                font-weight: bold;",
        "                letter-spacing: 2px;",
        "                color: white;",
        '                ">123434</span>PB</div>',
        
        '            <div class="item" style="',
        "                font-size: 0.18rem;",
        "                margin: 0.06rem 0 ;",
        "                font-weight: bold;",
        '            "  >数据总量<span style="',
        "                font-size: 0.2rem;",
        "                font-family: timeFont;",
        "                font-weight: bold;",
        "                letter-spacing: 2px;",
        "                color: white;",
        '                ">123434</span>PB</div>',
        
  
        '            <div class="btn" style="',
        "                display: inline-block;",
        "                padding: 0.02rem 0.06rem;",
        "                border: 1px solid #00ff78;",
        "                border-radius: 0.04rem;",
        "                text-align: center;",
        "                color: #00ff78;",
        "                font-size: 0.14rem;",
        '            ">隐藏阵地流量</div>',
        "    </div>",
        "    </div>",
        "  </div>",
      ].join("");
      return html;
    },
  };
  
export default tooltip